project:
  type: website
  output-dir: docs

website:
  title: "Avinash Reddy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - text: CV
        file: cv/Avinash_cv.pdf
        target: _blank

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



